"""Markdown exporter: human/AI readable pages, one folder per section.

Rendering is deterministic — volatile values (timestamps) are deliberately kept out of
the pages so identical ERP state yields identical Markdown (clean Git diffs). The single
place a timestamp appears is ``snapshot.json`` meta.
"""

from __future__ import annotations

import json

from dev_vigilante.exporters.base import Exporter, md_table, safe_filename, yesno

# collector -> (folder, render_mode)
_LAYOUT = {
    "system_info": ("system", "single"),
    "custom_fields": ("custom_fields", "grouped"),
    "client_scripts": ("scripts/client", "object"),
    "server_scripts": ("scripts/server", "object"),
    "custom_doctypes": ("doctypes", "object"),
}

_SECTION_TITLES = {
    "system_info": "System Information",
    "custom_fields": "Custom Fields",
    "client_scripts": "Client Scripts",
    "server_scripts": "Server Scripts",
    "custom_doctypes": "Custom DocTypes",
}


def _scalar(value) -> str:
    if isinstance(value, (dict, list)):
        return "`" + json.dumps(value, sort_keys=True, default=str) + "`"
    if isinstance(value, bool):
        return yesno(value)
    return "" if value is None else str(value)


def _unique_path(folder: str, stem: str, used: set[str]) -> str:
    """Path for a page, suffixing -2, -3... when distinct names slugify identically.

    Callers iterate artifacts in sorted key order, so suffixes are deterministic.
    """
    rel = f"{folder}/{stem}.md"
    n = 2
    while rel.lower() in used:
        rel = f"{folder}/{stem}-{n}.md"
        n += 1
    used.add(rel.lower())
    return rel


class MarkdownExporter(Exporter):
    name = "markdown"

    def __init__(self, link_machine_readable: bool = True):
        # False when the JSON files are not part of the same export (Markdown only).
        self.link_machine_readable = link_machine_readable

    def build_files(self, snapshot: dict) -> dict:
        artifacts = snapshot.get("artifacts", {})
        by_collector: dict[str, list] = {}
        for key in sorted(artifacts):
            a = artifacts[key]
            by_collector.setdefault(a.get("collector"), []).append(a)

        files: dict[str, str] = {}
        # collector -> list of (title, relpath) for the index
        index: dict[str, list] = {}
        # Case-insensitive so the tree also checks out cleanly on Windows/macOS.
        used_paths: set[str] = set()

        for collector in sorted(by_collector):
            items = sorted(by_collector[collector], key=lambda a: a.get("key", ""))
            folder, mode = _LAYOUT.get(collector, (collector, "object"))

            if mode == "grouped":
                groups: dict[str, list] = {}
                for a in items:
                    groups.setdefault(a.get("group") or "Ungrouped", []).append(a)
                for group in sorted(groups):
                    rel = _unique_path(folder, safe_filename(group), used_paths)
                    files[rel] = self._render_group(group, groups[group])
                    index.setdefault(collector, []).append((group, rel))
            else:
                for a in items:
                    rel = _unique_path(folder, safe_filename(a.get("name")), used_paths)
                    files[rel] = self._render_object(a)
                    index.setdefault(collector, []).append((a.get("name"), rel))

        files["README.md"] = self._render_readme(snapshot, by_collector, index)
        if snapshot.get("changes") is not None:
            files["changelog/CHANGES.md"] = self._render_changes(snapshot["changes"])
        if snapshot.get("dependency_graph") is not None:
            files["dependency/dependency_graph.md"] = self._render_dependency(
                snapshot["dependency_graph"]
            )
        return files

    # --- index ------------------------------------------------------------------

    def _render_readme(self, snapshot, by_collector, index) -> str:
        counts = (snapshot.get("meta") or {}).get("counts", {})
        lines = [
            "# Developer Snapshot",
            "",
            "Generated by **Dev Vigilante** — a complete inventory of the ERP's "
            "customization layer, optimized for humans and AI assistants.",
            "",
            "## Inventory",
            "",
            md_table(
                ["Section", "Count"],
                [
                    [_SECTION_TITLES.get(c, c), counts.get(c, len(by_collector[c]))]
                    for c in sorted(by_collector)
                ]
                + [["**Total**", counts.get("total", "")]],
            ),
            "",
        ]

        changes = snapshot.get("changes") or {}
        summary = changes.get("summary") or {}
        if summary:
            lines += [
                "## Changes Since Previous Snapshot",
                "",
                f"- Added: **{summary.get('added', 0)}**",
                f"- Removed: **{summary.get('removed', 0)}**",
                f"- Modified: **{summary.get('modified', 0)}**",
                "",
                "See [changelog/CHANGES.md](changelog/CHANGES.md).",
                "",
            ]

        lines += ["## Contents", ""]
        for collector in sorted(index):
            lines.append(f"### {_SECTION_TITLES.get(collector, collector)}")
            lines.append("")
            for title, rel in sorted(index[collector], key=lambda x: x[1]):
                lines.append(f"- [{title}]({rel})")
            lines.append("")

        if not self.link_machine_readable:
            return "\n".join(lines) + "\n"
        lines += [
            "## Machine-readable output",
            "",
            "- [snapshot.json](snapshot.json) — full structured snapshot",
            "- [search.json](search.json) — full-text search index",
            "- [dependency/dependency_graph.json](dependency/dependency_graph.json)",
            "",
        ]
        return "\n".join(lines) + "\n"

    # --- grouped (custom fields) ------------------------------------------------

    def _render_group(self, group: str, items: list) -> str:
        lines = [f"# Custom Fields — {group}", ""]
        rows = []
        for a in items:
            f = a.get("fields", {})
            rows.append(
                [
                    f.get("fieldname"),
                    f.get("label"),
                    f.get("field_type"),
                    f.get("options"),
                    yesno(f.get("mandatory")),
                    yesno(f.get("read_only")),
                    yesno(f.get("hidden")),
                    f.get("insert_after"),
                    f.get("fetch_from"),
                    f.get("depends_on"),
                ]
            )
        lines.append(
            md_table(
                [
                    "Fieldname",
                    "Label",
                    "Type",
                    "Options",
                    "Mandatory",
                    "Read Only",
                    "Hidden",
                    "Insert After",
                    "Fetch From",
                    "Depends On",
                ],
                rows,
            )
        )
        lines.append("")
        lines.append("## Details")
        lines.append("")
        for a in items:
            f = a.get("fields", {})
            lines.append(f"### {f.get('fieldname')}")
            lines.append("")
            if a.get("summary"):
                lines.append(f"> {a['summary']}")
                lines.append("")
            if f.get("description"):
                lines.append(f.get("description"))
                lines.append("")
            if f.get("default") not in (None, ""):
                lines.append(f"- Default: `{f.get('default')}`")
                lines.append("")
        return "\n".join(lines) + "\n"

    # --- per-object -------------------------------------------------------------

    def _render_object(self, a: dict) -> str:
        collector = a.get("collector")
        if collector in ("client_scripts", "server_scripts"):
            return self._render_script(a)
        if collector == "custom_doctypes":
            return self._render_doctype(a)
        if collector == "system_info":
            return self._render_system(a)
        return self._render_generic(a)

    def _render_header(self, a: dict) -> list:
        lines = [f"# {a.get('type')}: {a.get('name')}", ""]
        if a.get("summary"):
            lines += [f"> {a['summary']}", ""]
        return lines

    def _render_dependencies(self, a: dict) -> list:
        deps = a.get("dependencies") or []
        if not deps:
            return []
        lines = ["## Dependencies", ""]
        for dep in deps:
            lines.append(f"- {dep.get('type')}: `{dep.get('name')}`")
        lines.append("")
        return lines

    def _render_script(self, a: dict) -> str:
        f = a.get("fields", {})
        lines = self._render_header(a)
        meta_rows = [[k.replace("_", " ").title(), _scalar(v)] for k, v in sorted(f.items())]
        lines += ["## Properties", "", md_table(["Property", "Value"], meta_rows), ""]
        lines += self._render_dependencies(a)
        raw = (a.get("raw") or {}).get("script")
        if raw:
            lang = "js" if a.get("collector") == "client_scripts" else "python"
            lines += ["## Source", "", f"```{lang}", raw.rstrip("\n"), "```", ""]
        return "\n".join(lines) + "\n"

    def _render_doctype(self, a: dict) -> str:
        f = a.get("fields", {})
        lines = self._render_header(a)

        meta = [
            ["Module", f.get("module")],
            ["Custom (UI-created)", yesno(f.get("custom"))],
            ["Child Table", yesno(f.get("is_child_table"))],
            ["Single", yesno(f.get("is_single"))],
            ["Submittable", yesno(f.get("is_submittable"))],
            ["Track Changes", yesno(f.get("track_changes"))],
            ["Autoname", (f.get("naming") or {}).get("autoname")],
            ["Title Field", (f.get("naming") or {}).get("title_field")],
        ]
        lines += ["## Overview", "", md_table(["Property", "Value"], meta), ""]

        fields = f.get("fields") or []
        if fields:
            rows = [
                [
                    fld.get("fieldname"),
                    fld.get("label"),
                    fld.get("fieldtype"),
                    fld.get("options"),
                    yesno(fld.get("reqd")),
                    yesno(fld.get("read_only")),
                    yesno(fld.get("hidden")),
                ]
                for fld in fields
            ]
            lines += [
                "## Fields",
                "",
                md_table(
                    ["Fieldname", "Label", "Type", "Options", "Mandatory", "Read Only", "Hidden"],
                    rows,
                ),
                "",
            ]

        perms = f.get("permissions") or []
        if perms:
            rows = [
                [
                    p.get("role"),
                    p.get("permlevel"),
                    yesno(p.get("read")),
                    yesno(p.get("write")),
                    yesno(p.get("create")),
                    yesno(p.get("delete")),
                    yesno(p.get("submit")),
                    yesno(p.get("cancel")),
                ]
                for p in perms
            ]
            lines += [
                "## Permissions",
                "",
                md_table(
                    ["Role", "Level", "Read", "Write", "Create", "Delete", "Submit", "Cancel"],
                    rows,
                ),
                "",
            ]

        if f.get("child_tables"):
            lines += ["## Child Tables", ""]
            for c in f["child_tables"]:
                lines.append(f"- `{c.get('fieldname')}` → {c.get('child_doctype')}")
            lines.append("")

        if f.get("workflows"):
            lines += ["## Workflows", ""]
            for wf in f["workflows"]:
                lines.append(f"- {wf}")
            lines.append("")

        lines += self._render_dependencies(a)
        return "\n".join(lines) + "\n"

    def _render_system(self, a: dict) -> str:
        f = a.get("fields", {})
        lines = self._render_header(a)
        versions = f.get("versions", {})
        lines += [
            "## Versions",
            "",
            md_table(
                ["Component", "Version"],
                [[k, versions.get(k)] for k in sorted(versions)],
            ),
            "",
            "## Installed Apps",
            "",
        ]
        for app in f.get("installed_apps", []):
            ver = (f.get("app_versions") or {}).get(app)
            lines.append(f"- {app}" + (f" ({ver})" if ver else ""))
        lines.append("")
        if f.get("custom_apps"):
            lines += ["## Custom Apps", ""]
            for app in f["custom_apps"]:
                lines.append(f"- {app}")
            lines.append("")
        lines += [
            "## System Settings",
            "",
            md_table(
                ["Setting", "Value"],
                [[k, v] for k, v in sorted((f.get("system_settings") or {}).items())],
            ),
            "",
        ]
        return "\n".join(lines) + "\n"

    def _render_generic(self, a: dict) -> str:
        f = a.get("fields", {})
        lines = self._render_header(a)
        rows = [[k.replace("_", " ").title(), _scalar(v)] for k, v in sorted(f.items())]
        lines += ["## Properties", "", md_table(["Property", "Value"], rows), ""]
        lines += self._render_dependencies(a)
        return "\n".join(lines) + "\n"

    # --- changelog & dependency -------------------------------------------------

    def _render_changes(self, changes: dict) -> str:
        s = changes.get("summary", {})
        lines = [
            "# Changes Since Previous Snapshot",
            "",
            f"- **Added:** {s.get('added', 0)}",
            f"- **Removed:** {s.get('removed', 0)}",
            f"- **Modified:** {s.get('modified', 0)}",
            "",
        ]
        for bucket, title in (("added", "Added"), ("removed", "Removed"), ("modified", "Modified")):
            entries = changes.get(bucket) or []
            if not entries:
                continue
            lines += [f"## {title}", ""]
            for e in entries:
                extra = ""
                if e.get("changed_fields"):
                    extra = f" — changed: {', '.join(e['changed_fields'])}"
                lines.append(f"- **{e.get('type')}**: {e.get('name')}{extra}")
            lines.append("")
        return "\n".join(lines) + "\n"

    def _render_dependency(self, graph: dict) -> str:
        nodes = graph.get("nodes", [])
        edges = graph.get("edges", [])
        lines = [
            "# Dependency Graph",
            "",
            f"{graph.get('node_count', 0)} nodes · {graph.get('edge_count', 0)} edges.",
            "",
            "```mermaid",
            "graph LR",
        ]
        # Assign a stable, mermaid-safe id to each node, then declare edges by id so
        # each node appears once.
        node_id = {n["id"]: f"N{i}" for i, n in enumerate(nodes)}
        for n in nodes:
            label = (n.get("label") or n["id"]).replace('"', "'")
            lines.append(f'  {node_id[n["id"]]}["{label}"]')
        for edge in edges:
            src = node_id.get(edge["from"])
            dst = node_id.get(edge["to"])
            if src and dst:
                lines.append(f"  {src} --> {dst}")
        lines += ["```", ""]
        return "\n".join(lines) + "\n"
